name: rdev_riverpod_firebase_auth
description: This package provides a simple way to use Firebase Auth with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.3.0

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: ^0.5.0
  rdev_errors_logging: ^0.3.0
  ### 3rd party
  cloud_functions: ^6.0.5
  equatable: ^2.0.7
  firebase_auth: ^6.1.3
  firebase_auth_platform_interface: ^8.1.5
  flutter_facebook_auth: ^7.1.2
  flutter_hooks: ^0.21.3+1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  hooks_riverpod: ^3.1.0
  talker: ^5.1.9
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  build_runner: ^2.10.4
  cloud_functions_platform_interface: ^5.8.8
  firebase_core: ^4.3.0
