name: rdev_riverpod_firebase
description: This package provides a simple way to use Firebase with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.5.1

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_errors_logging: any
  ### 3rd party
  cloud_firestore: 6.1.1
  cloud_functions: 6.0.5
  firebase_analytics: 12.1.0
  firebase_auth: 6.1.3
  firebase_core: 4.3.0
  # firebase_dynamic_links: ^5.4.14
  firebase_storage: 13.0.5
  firebase_messaging: 16.1.0
  flutter_facebook_auth: ^7.1.2
  flutter_hooks: ^0.21.3+1
  google_sign_in: ^7.2.0
  hooks_riverpod: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
