name: rdev_riverpod_stored_file
description: Manage files
repository: https://github.com/r-dev-limited/placebo-life
version: 0.3.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_errors_logging:
  rdev_riverpod_firebase:
  rdev_helpers:
  ### 3rd party
  cloud_firestore: 5.6.9
  cloud_functions: 5.5.2
  equatable: ^2.0.7
  firebase_storage: 12.4.7
  json_annotation: ^4.9.0
  mime: ^2.0.0
  talker: ^4.7.1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
