name: rdev_riverpod_stored_file
description: Manage files
repository: https://github.com/r-dev-limited/placebo-life
version: 0.4.0

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_errors_logging:
  rdev_riverpod_firebase:
  rdev_helpers:
  ### 3rd party
  cloud_firestore: 6.1.1
  cloud_functions: 6.0.5
  equatable: ^2.0.7
  firebase_storage: 13.0.5
  json_annotation: ^4.9.0
  mime: ^2.0.0
  talker: ^5.1.9
  hooks_riverpod: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
