name: rdev_riverpod_versioning
description: This package provides a simple way to use Firebase User with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.4.0

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: ^0.5.0
  rdev_errors_logging: ^0.3.0
  rdev_helpers: ^0.3.0
  ### 3rd party
  device_info_plus: ^12.3.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  hooks_riverpod: ^3.1.0
  logging: ^1.3.0
  cloud_firestore: 6.1.1
  firebase_core: 4.3.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
