name: rdev_riverpod_messaging
description: This package provides a simple way to use Firebase Auth updated via User
repository: https://github.com/r-dev-limited/placebo-life
version: 0.0.16+1

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: any
  rdev_riverpod_firebase_auth: ^0.3.1
  rdev_riverpod_firebase_user: ^0.6.0+1
  rdev_errors_logging: any
  rdev_helpers: ^0.3.1
  ### 3rd party
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  hooks_riverpod: ^3.1.0
  talker: ^5.1.9
  cloud_firestore: 6.1.1
  cloud_functions: 6.0.5
  firebase_messaging: 16.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
