name: rdev_helpers
description: This package provides different utils.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.3.0

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  ### 3rd party
  json_annotation: ^4.9.0
  overlay_support: 2.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  json_serializable: ^6.11.2
