name: rdev_riverpod_purchases
description: Manage purchases
repository: https://github.com/r-dev-limited/placebo-life
version: 0.3.0

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_errors_logging: ^0.3.0
  rdev_riverpod_firebase: ^0.5.0
  rdev_helpers: ^0.3.0
  ### 3rd party
  cloud_firestore: 6.1.1
  cloud_functions: 6.0.5
  equatable: ^2.0.7
  flutter_inapp_purchase: ^8.2.0
  json_annotation: ^4.9.0
  talker: ^5.1.9
  hooks_riverpod: ^3.1.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
