name: rdev_errors_logging
description: This package provides a simple way to log errors.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.3.0

environment:
  sdk: '>=3.10.4 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ### 3rd party
  connectivity_plus: ^7.0.0
  googleapis_auth: ^2.0.0
  googleapis: ^15.0.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  talker: ^5.1.9
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
